package es.jysa.priceCalculatorNG;

import java.awt.EventQueue;
import java.util.logging.Level;

import es.jysa.priceCalculatorNG.gui.MainFrame;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	
	private Controller controller;
	private MainFrame view;
	
	public App () {
//		String configPath = "configTest.json";
//		String productsPath = "products.csv";
//		String pricesPath = "DPS_Prices.txt";
//		String tmpPath = "";
//		String destinationPath = "prueba.csv";
//		Character delimiter = ';';
//		Character quote = '"';
//		
//		Controller controller = PrestaFactory.getController(configPath, tmpPath, delimiter, quote);
//		
//		controller.loadPrestaData(productsPath);
//		controller.setPriceProviderPioneer(pricesPath);
//		controller.getNewPrices();
//		controller.exportNewPrices(destinationPath);
		
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					view = new MainFrame();
				} catch (Exception e) {
					System.exit(1);
				}
			}
		});
	}
	

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
    	new App();
    	
    }
}
